version: '3.9'

services:
  backend:
    build:
      context: ./orchestratai_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - orchestratai-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: orchestratai_client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    depends_on:
      - backend
    networks:
      - orchestratai-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - orchestratai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

volumes:
  redis_data:

networks:
  orchestratai-network:
